#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR="vim"

#
## Aliases
#
alias findhere='find . -maxdepth 1 -name'
alias lss='ls -Al'
alias ppjson='python -m"json.tool"'
alias findd="find . -type f -name"
alias findir="find . -x -type d -name"

alias start_postgres='pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start'
alias stop_postgres='pg_ctl -D /usr/local/var/postgres stop -s -m fast'

#
## Git aliases
#
alias git-rm-merged='git branch --merged | grep -v "\*" | xargs -n 1 git branch -d'
alias git-rm-files="git ls-files -d -z | xargs -0 git rm"
alias git-copy-br='git branch | grep "\*" | cut -c 3- | xargs echo -n | pbcopy'
alias last-commit="git log --pretty=oneline -n1 | cut -c 1-6 | tr '[a-z]' '[A-Z]'"
alias gp='git pull'
alias gpullo='CURRENT_BRANCH=`git branch | grep "\*" | cut -c 3- | xargs echo -n` && git pull origin ${CURRENT_BRANCH}'
alias gpusho='CURRENT_BRANCH=`git branch | grep "\*" | cut -c 3- | xargs echo -n` && git push origin ${CURRENT_BRANCH}'
alias gst='git status'
alias glg='git lg'

#function ghelp
#    echo "* git-rm-merged deletes all merged branches. Should be called from master branch"
#    echo "* git-rm-file   removes all deleted files"
#    echo "* git-copy-br   copy the current branch to the clipboard"
#    echo "* last-commit   list the sha of the last commit"
#    echo "* gp            git pull"
#    echo "* gcommit       commits with a required message"
#    echo "* gst           git status"
#    echo "* glg           git lg"
#end

unsetopt CORRECT

#
## RBENV
#
# TODO: Setup  rbenv
# eval "$(rbenv init -)"

if [[ -s "${ZDOTDIR:-$HOME}/.zlocal" ]]; then
  source "${ZDOTDIR:-$HOME}/.zlocal"
fi
